# Generated by Django 4.2.7 on 2023-11-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price_for_new", models.IntegerField()),
                ("price_for_old", models.IntegerField()),
                ("event_photo_id", models.CharField(max_length=50)),
                ("ticket_photo_id", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MemberGirl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("unique_id", models.CharField(max_length=50)),
                ("discussion_topics", models.TextField()),
                ("joining_purpose", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_id", models.CharField(max_length=50)),
                ("text", models.TextField()),
            ],
        ),
    ]
